"""Streamlit UI for PRE-GEN detect."""

from __future__ import annotations

import html

from dotenv import load_dotenv
import streamlit as st

from app.extractor import VideoExtractionError, extract_mp4_url
from app.openai_client import ArbitrationError, Verdict, arbitrate
from app.twelvelabs_client import TwelveLabsError, describe_primary_subject

load_dotenv()

st.set_page_config(page_title="PRE-GEN detect", page_icon="🛡️", layout="centered")
st.markdown(
    """
    <style>
      #MainMenu, header, footer { visibility: hidden; }
      .stApp { background: #fff; color: #000; }
      .block-container {
        box-sizing: border-box; max-width: 760px !important; margin: 48px auto !important;
        padding: 28px !important; border: 2px solid #000; border-radius: 0 !important;
        box-shadow: 10px 10px 0 #000;
      }
      h1 { margin: 0 0 8px !important; font-size: 2rem !important; letter-spacing: -0.04em; }
      .intro { margin: 0 0 4px; color: #000; line-height: 1.5; }
      div[data-testid="stForm"] { border: 0 !important; padding: 0 !important; }
      div[data-testid="stWidgetLabel"] p { color: #000 !important; font-weight: 650 !important; }
      div[data-testid="stTextInput"] input, div[data-testid="stTextArea"] textarea {
        border: 2px solid #000 !important; border-radius: 0 !important; background: #fff !important;
        color: #000 !important; padding: 10px 12px !important; box-shadow: none !important;
      }
      div[data-testid="stTextArea"] textarea { min-height: 150px !important; }
      div.stButton > button, div[data-testid="stFormSubmitButton"] > button {
        margin-top: 8px; border: 2px solid #000 !important; border-radius: 0 !important;
        background: #000 !important; color: #fff !important; padding: 12px 18px !important;
        font-weight: 700 !important; box-shadow: none !important;
      }
      div.stButton > button:hover, div[data-testid="stFormSubmitButton"] > button:hover {
        background: #fff !important; color: #000 !important;
      }
      .status-message { margin: 24px 0 0; line-height: 1.5; }
      .result-panel { margin-top: 22px; border: 2px solid #000; border-radius: 0; padding: 18px; }
      .result-panel.decline { background: #000; color: #fff; }
      .result-panel.approve { background: #fff; color: #000; }
      .result-panel .verdict { font-size: 1.5rem; font-weight: 800; }
      .result-panel p, .result-panel pre { color: inherit; }
      .result-panel pre { margin: 16px 0 0; white-space: pre-wrap; font: inherit; line-height: 1.45; }
      div[data-testid="stAlert"] { border-radius: 0 !important; border: 2px solid #000 !important; }
      @media (max-width: 640px) {
        .block-container { margin: 20px !important; padding: 20px !important; box-shadow: 7px 7px 0 #000; }
      }
    </style>
    """,
    unsafe_allow_html=True,
)

st.title("PRE-GEN detect")
st.markdown(
    '<p class="intro">Buddian asks: does this generated video violate copyright? '
    "Ambiguity blocks distribution.</p>",
    unsafe_allow_html=True,
)

with st.form("validation-form", border=False):
    video_url = st.text_input(
        "Video generated by Buddian",
        placeholder="https://buddian.com/app/video?id=241",
    )
    protected_description = st.text_area(
        "Prampta protected subject description",
        placeholder="Describe the protected subject without relying on a name.",
        height=150,
    )
    submitted = st.form_submit_button("Ask PRE-GEN detect", type="primary")

status_placeholder = st.empty()
result_placeholder = st.empty()


def show_status(message: str) -> None:
    status_placeholder.markdown(
        f'<p class="status-message">{html.escape(message)}</p>', unsafe_allow_html=True
    )


if submitted:
    if not video_url.strip() or not protected_description.strip():
        st.error("Both the video URL and protected description are required.")
    else:
        try:
            show_status("Buddian video received → resolving media…")
            mp4_url = extract_mp4_url(video_url)
            show_status("Buddian video received → visual analysis…")
            visual_description = describe_primary_subject(mp4_url)
            show_status("Buddian video received → visual analysis → copyright decision…")
            result: Verdict = arbitrate(protected_description, visual_description)
        except (VideoExtractionError, TwelveLabsError, ArbitrationError) as exc:
            show_status(f"Blocked: {exc}")
        else:
            is_decline = result.verdict == "DECLINE"
            panel_class = "decline" if is_decline else "approve"
            verdict_text = (
                "COPYRIGHT VIOLATION: YES — DECLINE"
                if is_decline
                else "COPYRIGHT VIOLATION: NO — APPROVE"
            )
            result_placeholder.markdown(
                "<section class=\"result-panel "
                f"{panel_class}\"><div class=\"verdict\">{verdict_text}</div>"
                f"<p>{html.escape(result.reasoning)}</p>"
                f"<pre>{html.escape(visual_description)}</pre></section>",
                unsafe_allow_html=True,
            )
            show_status(f"Resolved media: {mp4_url}")
